/*
	CSC D84 - Unit 1 - Search

	This file contains stubs for implementing the different search
	algorithms covered in the course. Please read the assignment
	handout carefully - it describes the game, the data you will
	have to handle, and the search functions you must provide.

	Once you have read the handout carefully, implement your search
	code in the sections below marked with

	**************
	*** TO DO:
	**************

	Make sure to add it to your report.txt file - it will be marked!

	Have fun!

	DO NOT FORGET TO 'valgrind' YOUR CODE - We will check for pointer
	management being done properly, and for memory leaks.

	Starter code: F.J.E., Jul. 15
	Updated: F.J.E., Jan. 18
*/

/**********************************************************************
% COMPLETE THIS TEXT BOX:
%
% 1) Student Name:	Kemar Harris
%
% 1) Student number: 1003410588
% 
% 1) harri471
% 
% We hereby certify that the work contained here is our own
%
% Kemar Harris            
% (sign with your name)            (sign with your name)
***********************************************************************/

#include "AI_search.h"

 /*
   This function is the interface between your solution for the assignment and the driver code. The driver code
   in AI_search_core_GL will call this function once per frame, and provide the following data
   
   Board and game layout:
	
	The game takes place on a grid of size 32x32, the file board_layout.h specifies the size and defines two
	constants 'size_X' and 'size_Y' for the horizontal and vertical size of the board, respectively. For our
	purposes, the grid of locations is represented by a graph with one node per grid location, so given
	the 32x32 cells, the graph has 1024 nodes. 

	To create a maze, we connect cell locations in the grid in such a way that a) there is a path from any
	grid location to any other grid location (i.e. there are no disconnected subsets of nodes in the graph),
	and b) there are loops.

	Since each node represents a grid location, each node can be connected to up to 4 neighbours in the
	top, right, bottom, and left directions respectively:

			node at (i,j-1)
				^
				|
	(node at i-1, j) <- node at (i,j) -> node at (i+1, j)
				|
				v
			node at (i,j+1)

	The graph is theredore stored as an adjacency list with size 1024 x 4, with one row per node in the
	graph, and 4 columns corresponding to the weight of an edge linking the node with each of its 4
	possible neighbours in the order towp, right, bottom, left (clockwise from top).

	Since all we care is whether nodes are connected. Weights will be either 0 or 1, if the weight is
	1, then the neighbouring nodes are connected, if the weight is 0, they are not. For example, if

	graph[i][0] = 0 
	graph[i][1] = 1
	graph[i][2] = 0
	graph[i][3] = 1

	then node i is connected to the right and left neighbours, but not to top or bottom.

	The index in the graph for the node corresponding to grid location (x,y) is

	index = x + (y*size_X) 		or in this case		index = x + (y*32)

	Conversely, if you have the index and want to figure out the grid location,

	x = index % size_X		or in this case		x = index % 32
	y = index / size_Y		or in this case		y = index / 32

	(all of the above are *integer* operations!)

	A path is a sequence of (x,y) grid locations. We store it using an array of size	
	1024 x 2 (since there are 1024 locations, this is the maximum length of any
	path that visits locations only once).

	Agent locations are coordinate pairs (x,y)	

   Arguments:
		gr[graph_size][4]   - This is an adjacency list for the maze
		path[graph_size][2] - An initially empty path for your code to fill.
				      In this case, empty means all entries are initially -1
		visit_order[size_X][size_Y]	- An array in which your code will store the
						  *order* in which grid locations were 
						  visited during search. For example, while
						  doing BFS, the initial location is the
						  start location, it's visit order is 1.
						  Then the search would expand the immediate
						  neighbours of the initial node in some order,
						  these would get a visit order of 2, 3, 4, and
						  5 respectively, and so on.
					
						  This array will be used to display the search
						  pattern generated by each search method.

		cat_loc[10][2], cats   - Location of cats and number of cats (we can have at most 10,
					 but there can be fewer). Only valid cat locations are 0 to (cats-1)
		cheese_loc[10][2], cheeses - Location and number of cheese chunks (again at most 10,
					     but possibly fewer). Valid locations are 0 to (cheeses-1)
		mouse_loc[1][2] - Mouse location - there can be only one!
		mode - Search mode selection:
					mode = 0 	- BFS
					mode = 1	- DFS
					mode = 2	- A*

		(*heuristic)(int x, int y, int cat_loc[10][2], int cheese_loc[10][2], int mouse_loc[10][2], int cats, int cheeses)
				- This is a pointer to one of the heuristic functions you will implement, either H_cost()
				  or H_cost_nokitty(). The driver in AI_search_core_GL will pass the appropriate pointer
				  depending on what search the user wants to run.
			
				  If the mode is 0 or 1, this pointer is NULL

				  * How to call the heuristic function from within this function : *
					- Like any other function:
						h = heuristic( x, y, cat_loc, cheese_loc, mouse_loc, cats, cheeses);

   Return values:
		Your search code will directly update data passed-in as arguments:

		- path[graph_size][2]	: Your search code will update this array to contain the path from
					  the mouse to one of the cheese chunks. The order matters, so
					  path[0][:] must be the mouse's current location, path[1][:]
					  is the next move for the mouse. Each successive row will contain
					  the next move toward the cheese, and the path ends at a location
					  whose coordinates correspond to one of the cheese chunks.
					  Any entries beyond that must remain set to -1
		- visit_order[size_X][size_Y] 	:  Your search code will update this array to contain the
						   order in which each location in the grid was expanded
						   during search. This means, when that particular location
						   was checked for being a goal, and if not a goal, had its
						   neighbours added as candidates for future expansion (in
						   whatever order is dictated by the search mode).

						   Note that since there are 1024 locations, the values in 
						   this array must always be in [0, 1023]. The driver code
						   will then display search order as a yellow-colored
						   brightness map where nodes expanded earlier will look
						   brighter.

		* Your code MUST NOT modify the locations or numbers of cats and/or cheeses, the graph,
	     	  or the location of the mouse - if you try, the driver code will know it *
			
		That's that, now, implement your solution!
 */

 /********************************************************************************************************
 * 
 * TO DO:	Implement code to carry out the different types of search depending on the
 *		mode.
 *
 *		You can do this by writing code within this single function (and being clever about it!)
 *		Or, you can use this function as a wrapper that calls a different search function
 *		 (BFS, DFS, A*) depending on the mode. Note that in the latter case, you will have
 *	    	  to inform your A* function somehow of what heuristic it's supposed to use.
 *
 *		Visiting Order: When adding the neighbours of a node to your list of candidates for
 *				expansion, do so in the order top, right, bottom, left.
 *
 *		NOTE: Your search functions should be smart enough to not choose a path that goes
 *		      through a cat! this is easily done without any heuristics.
 * 
 *		How you design your solution is up to you. But:
 *
 *		- Document your implementation by adding concise and clear comments in this file
 *		- Document your design (how you implemented the solution, and why) in the report
 *
 ********************************************************************************************************/

 // Stub so that the code compiles/runs - The code below will be removed and replaced by your code!

// int num_visited = 0;

void search(double gr[graph_size][4], int path[graph_size][2], int visit_order[size_X][size_Y], int cat_loc[10][2], int cats, int cheese_loc[10][2], int cheeses, int mouse_loc[1][2], int mode, int (*heuristic)(int x, int y, int cat_loc[10][2], int cheese_loc[10][2], int mouse_loc[1][2], int cats, int cheeses, double gr[graph_size][4]))
{
	int closest_cheese = closest(mouse_loc[0][0], mouse_loc[0][1], cheese_loc, cheeses);
    int goal = TO_INDEX(cheese_loc[closest_cheese][0], cheese_loc[closest_cheese][1]);
    int start = TO_INDEX(mouse_loc[0][0], mouse_loc[0][1]);

    // bfs
    if (mode == 0) {
        BFS(gr, start, goal, path, visit_order, cat_loc, cats);

    } else if (mode == 1) { // dfs
        int seen[graph_size];
        init_seen(seen);
        int depth = 0;

        DFS(gr, start, goal, seen, path, depth, visit_order, cat_loc, cats);

        int order = 1;
        for (int i = 0; i < graph_size; i++) {
            if (seen[i] != -1) {
                update_visited(seen[i], visit_order, order);
				order ++;
            }
        }
    } else if (mode == 2) { // A*

        A_STAR(gr, start, goal, path, visit_order, cat_loc, cats, cheese_loc, mouse_loc, cheeses, heuristic);
    }
 	return;
}

void BFS(double graph[graph_size][4], int start, int goal, int path[graph_size][2], int visit_order[size_X][size_Y], int cat_loc[10][2], int cats) {
    // bfs code
    // implementation of BFS

    int seen[graph_size];
    int pred[graph_size];
    int priority_queue[graph_size][2];
    int num_visited = 1;
    

    init_seen(seen);
    init_seen(pred);
    init_queue(priority_queue);

	// add start node to queueint priority_queue[graph_size][2];
    update_queue(priority_queue, start, 0);
	// found marker
    int found = 0;
	// while the queue is not empty and not found
    while (!queue_is_empty(priority_queue) && !found)
    {

        
        // get next node u from pq
        int u = get_next(priority_queue);
        // mark u as seen
        add_to_set(seen, u);

        update_visited(u, visit_order, num_visited);
        num_visited ++;

        if (u == goal) {
            found = 1;
        } else { // search
            // for all nodes v in u's adjacency list
            for (int i = 0; i < 4; i ++) {
                
                if (graph[u][i]) {
                    // re add v to queue, queue does not enable duplicates
                    int v = connected_index(u, i);
                    if (!set_contains(seen, v) && !cat_position(v, cat_loc, cats)) {
                        // set to discovered
                        add_to_set(seen, v);
                        // update the queu, bfs ignores priorty
                        update_queue(priority_queue, v, 0);
                        pred[v] = u;
                        
                    }
                }
            }   
        }
    }

    if (found) {
        int i = 0;
        int reverse_path[graph_size];
        int index = goal;
        while (index != start)
        {
            reverse_path[i] = index;
            index = pred[index];
            i ++;
        }
        reverse_path[i] = start;
        
        int j = 0;
        for (; i >= 0; i--) {
            int pos = reverse_path[i];
            path[j][0] = X_VALUE(pos);
            path[j][1] = Y_VALUE(pos);
            j ++;
        }
    }
}

int DFS(double graph[graph_size][4], int start, int goal, int seen[graph_size], int path[graph_size][2], int depth, int visit_order[size_X][size_Y], int cat_loc[10][2], int cats) {
    // recursive ver
	// if node is goal

    add_to_set(seen, start);

    if (start == goal) {
        // add to path
        path[depth][0] = X_VALUE(start);
        path[depth][1] = Y_VALUE(start);
	  // return found
        return 1;
    }
	// printf("%d\t", start);
	// mark node u as discovered
    
	// for each neighbour of u,
    for (int i = 0; i < 4; i++) {
        if (graph[start][i]) {
            int v = connected_index(start, i);
            // if node is not discovered 
            if (!set_contains(seen, v) && !cat_position(v, cat_loc, cats)) {
                // if dfs found node
                int found = DFS(graph, v, goal, seen, path, depth + 1, visit_order, cat_loc, cats);
                if (found) {
                    // add to path
                    path[depth][0] = X_VALUE(start);
                    path[depth][1] = Y_VALUE(start);
                    return 1;
                }
            }
        }
    }
	// if the code ever reaches here node was not found, display message
    return 0;
}

// basically the same as BFS but with a heuristic value and some extra distance values added
void A_STAR(double graph[graph_size][4], int start, int goal, int path[graph_size][2], int visit_order[size_X][size_Y], int cat_loc[10][2], int cats, int cheese_loc[10][2], int mouse_loc[1][2], int cheeses,
     int (*heuristic)(int x, int y, int cat_loc[10][2], int cheese_loc[10][2], int mouse_loc[1][2], int cats, int cheeses, double gr[graph_size][4])) {
    // bfs code
    // implementation of BFS
    int seen[graph_size];
    int pred[graph_size];
    int priority_queue[graph_size][2];
    int distance[graph_size];
    

    init_seen(seen);
    init_seen(pred);
    init_queue(priority_queue);
    set_distances(graph, distance, goal);

    int num_visited = 1;

	// add start node to queueint priority_queue[graph_size][2];
    update_queue(priority_queue, start, 0);
	// found marker
    int found = 0;
	// while the queue is not empty and not found
    while (!queue_is_empty(priority_queue) && !found)
    {   
        // get next node u from pq
        int u = get_next(priority_queue);
        // mark u as seen
        add_to_set(seen, u);

        update_visited(u, visit_order, num_visited);
        num_visited ++;

        if (u == goal) {
            found = 1;
        } else { // search
            // for all nodes v in u's adjacency list
            for (int i = 0; i < 4; i ++) {
                
                if (graph[u][i]) {
                    // re add v to queue, queue does not enable duplicates
                    int v = connected_index(u, i);
                    if (!set_contains(seen, v) && !cat_position(v, cat_loc, cats)) {
                        // set to discovered
                        add_to_set(seen, v);
                        // update the queue, bfs ignores priorty

                        int f = distance[v] + heuristic(X_VALUE(v), Y_VALUE(v), cat_loc, cheese_loc, mouse_loc, cats, cheeses, graph);
                        update_queue(priority_queue, v, f);
                        pred[v] = u;
                    }
                }
            }   
        }
    }

    if (found) {
        int i = 0;
        int reverse_path[graph_size];
        int index = goal;
        while (index != start)
        {
            reverse_path[i] = index;
            index = pred[index];
            i ++;
        }
        reverse_path[i] = start;
        
        int j = 0;
        for (; i >= 0; i--) {
            int pos = reverse_path[i];
            path[j][0] = X_VALUE(pos);
            path[j][1] = Y_VALUE(pos);
            j ++;
        }
    }
}

 /*
	This function computes and returns the heuristic cost for location x,y.
	As discussed in lecture, this means estimating the cost of getting from x,y to the goal. 
	The goal is cheese. Which cheese is up to you.
	Whatever you code here, your heuristic must be admissible.

	Input arguments:

		x,y - Location for which this function will compute a heuristic search cost
		cat_loc - Cat locations
		cheese_loc - Cheese locations
		mouse_loc - Mouse location
		cats - # of cats
		cheeses - # of cheeses
		gr - The graph's adjacency list for the maze

		These arguments are as described in the search() function above
 */
int H_cost(int x, int y, int cat_loc[10][2], int cheese_loc[10][2], int mouse_loc[1][2], int cats, int cheeses, double gr[graph_size][4])
{


	int mouse_x = mouse_loc[0][0];
    int mouse_y = mouse_loc[0][1];

    int min_cheese = closest(mouse_x, mouse_y, cheese_loc, cheeses);

    int cheese_x = cheese_loc[min_cheese][0];
    int cheese_y = cheese_loc[min_cheese][1];

    return euclidian_distance(x, y, cheese_x, cheese_y);
}

 /*
	This function computes and returns the heuristic cost for location x,y.
	As discussed in lecture, this means estimating the cost of getting from x,y to the goal. 
	The goal is cheese. 

	However - this time you want your heuristic function to help the mouse avoid being eaten.
	Therefore: You have to somehow incorporate knowledge of the cats' locations into your
	heuristic cost estimate. How well you do this will determine how well your mouse behaves
	and how good it is at escaping kitties.

	This heuristic *does not have to* be admissible.

	Input arguments have the same meaning as in the H_cost() function above.
 */
int H_cost_nokitty(int x, int y, int cat_loc[10][2], int cheese_loc[10][2], int mouse_loc[1][2], int cats, int cheeses, double gr[graph_size][4])
{
	// this follows the same idea as before, but now, we're avoiding casts as much as possible.
    // the idea is to move away from the closest cat.
    // take the maximum distance from the cat, and subtract the current manhattan distance from the mouse.
    // the manhattan distance will be more than the euclidean distance, so avoiding cats takes priorty over getting the cheese.

    int mouse_x = mouse_loc[0][0];
    int mouse_y = mouse_loc[0][1];

    int min_cat = closest(mouse_x, mouse_y, cat_loc, cats);

    int cat_x = cat_loc[min_cat][0];
    int cat_y = cat_loc[min_cat][1];
    // inverted so it returns the maximal distance
    int distance[graph_size];
    int next_index = TO_INDEX(x, y);
    set_distances(gr, distance, next_index);

    int cat_index= TO_INDEX(cat_x, cat_y);
    int d = - (distance[cat_index] + 1);

    return d;
}

// finds distance of closest object using manhattan distance
int closest(int x, int y, int thing_loc[10][2], int things) {
    int min_dist = INT_MAX;

    int min_thing = -1;

    int thing_x;
    int thing_y;
    // pick the distance of the cat thats closest to the mouse
    for (int i = 0; i < things; i++) {
        thing_x = thing_loc[i][0];
        thing_y = thing_loc[i][1];

        int d = abs(thing_x - x) + abs(thing_y - y);
        if (d < min_dist) {
            min_thing = i;
        }
    }
    return min_thing;
}

int cat_position(int index, int cat_loc[10][2], int cats) {
    int x = X_VALUE(index);
    int y = Y_VALUE(index);

    for (int i = 0; i < cats; i++) {
        if (cat_loc[i][0] == x && cat_loc[i][1] == y) {
            return 1;
        }
    }
    return 0;
}


int euclidian_distance(int x1, int y1, int x2, int y2) {
    double x = x2 - x1;
    double y = y2 - y1;
    double d = sqrt( pow(x, 2) + pow(y, 2));
    d = floor(d);
    int ret = d;
    return ret;
}

// a very similar copy of BFS that finds and sets the distance for all values in the graph using the distance array.
void set_distances(double graph[graph_size][4], int distance[graph_size], int index) {
    
    distance[index] = 0;
    int priority_queue[graph_size][2];
    init_queue(priority_queue);

    int seen[graph_size];
    init_seen(seen);

    update_queue(priority_queue, index, 0);

    while (!queue_is_empty(priority_queue)) {
        // get next node u from pq
        int u = get_next(priority_queue);
        // mark u as seen
        add_to_set(seen, u);

        for (int i = 0; i < 4; i ++) {
            if (graph[u][i]) {
                int v = connected_index(u, i);
                if (!set_contains(seen, v)) {
                    // add the value to queue
                    update_queue(priority_queue, v, 0);
                    // mark seen
                    add_to_set(seen, v);
                    // set distance
                    distance[v] = distance[u] + 1;
                }
            }
        }
    }
}

void update_visited(int index_visited, int visit_order[size_X][size_Y], int num_visited) {
    int x = X_VALUE(index_visited);
    int y = Y_VALUE(index_visited);

    visit_order[x][y] = num_visited;
}

void init_seen(int seen[graph_size]) {
    for (int i = 0; i < graph_size; i++) 
    {
        seen[i] = -1;
    }
}

int connected_index(int index, int direction) {
    int x = X_VALUE(index);
    int y = Y_VALUE(index);
    if (direction == 0) {
        y --;
    } else if (direction == 1) {
        x ++;
    } else if (direction == 2) {
        y ++;
    } else if (direction == 3) {
        x --;
    }

    if (x < 0 || y < 0 || x >= size_X || y >= size_Y) {
        printf("incorrect value of (%d, %d) at index %d in direction %d\n", x, y, index, direction);
        exit(1);
    }

    return TO_INDEX(x, y);
}

void add_to_set(int s[set_size], int value) {
    for (int i = 0; i < set_size; i ++) {
        if (s[i] == value) {
            return;
        } else if (s[i] == -1) {
            s[i] = value;
            return;
        }
    }
}

int set_contains(int s[set_size], int value) {
    for (int i = 0; i < set_size; i ++) {
        if (s[i] == value) {
            return 1;
        }
    }
    return 0;
}

int get_next(int q[][2]){
	int minimum_priority = INT_MAX;
	int index = -1;
	for (int i = 0; i < queue_size; i++) {
		// spot is not empty and smallest priority
		if (q[i][0] > -1 && q[i][1] < minimum_priority) {
			minimum_priority = q[i][1];
			index = i;
		}
	}
	if (index < 0) {
		return -1;
	}
	int ret_index = q[index][0];
	q[index][0] = -2; // spot taken, but not valid, necesarry for normal queue behaviour
	q[index][1] = INT_MAX;
	return ret_index;;
}

void update_queue(int q[][2], int value, int priority) {
	int free_spot = -1;
	for (int i = 0; i < queue_size; i++) {
		if (q[i][0] == value) {
			if (q[i][1] > priority) {
				q[i][1] = priority;
			}
			return;
		} else if (free_spot == -1 && q[i][0] == -1) {
			free_spot = i;
		}
	}
	// not in queue so update
	q[free_spot][0] = value;
	q[free_spot][1] = priority;
}

void init_queue(int q[][2]) {
    for (int i = 0; i < queue_size; i ++) 
    {
        q[i][0] = -1;
        q[i][1] = INT_MAX;
    }
}

int queue_is_empty(int q[][2]) {
    for (int i = 0; i < queue_size; i ++)
    {
        if (q[i][0] > -1) {
            return 0;
        }
    }
    return 1;
}
